from abc import ABC, abstractmethod

class AbstractRepository(ABC):
    @abstractmethod
    def get_by_id(self, entity_id): ...
    @abstractmethod
    def get_all(self) -> list: ...
    @abstractmethod
    def save(self, entity) -> None: ...
    @abstractmethod
    def delete(self, entity_id) -> None: ...